First Draft of Async EP 2
devleague/The-Async-Force-Ep-2 pull request #1
Opened 2016-12-15 06:04 UTC by TheWhiteOx

Just put an Input and Button element in the index.

The README as compared to EP1 tells them to scrape data from the input field and the next step is a rather open ended: "Use the data from the API to display information in a presentable way, you will have to add some HTML elements in the index.html file" kind of thing.

And an additional "Handle errors from the API calls gracefully"

Should I add more requirements?

2016-12-15 06:06 UTC, theRemix requested changes

2016-12-15 06:06 UTC, theRemix commented on README.md
> +1. Think of an elegant way of handling errors.  For example, if the SWAPI API returns an error due to incorrect an incorrect URL fragment.
Display any xhr errors in the dom, so the user can see.
for example, if a user inputs `99999` as an id, or `potato`
display the error on the page

2016-12-15 06:07 UTC, theRemix requested changes
add explanation of what *URL Fragment* is, 
maybe provide an example.

2016-12-15 06:09 UTC, theRemix requested changes
add more instructions

2016-12-15 06:09 UTC, theRemix commented on index.html
> +  <button>Hit the Swapi API!</button>
change the button to read "Get Person from SWAPI"

2016-12-15 06:09 UTC, theRemix commented on README.md
> +  Information from the data that comes back from the API should be displayed in
add some more goals to the readme.
The developer should start by requesting the `/people/:id` api
then, describe what should be displayed
ex:

> Display this person's name
> Display all film titles that this person appeared in
> Display all planets this person has visited

2016-12-15 07:15 UTC, TheWhiteOx commented
1. Added short explanation of URL fragment in hints section. 
2. Changed button name to "Get Person from SWAPI".
3. Reworded XHR error step.
4. Added additional data display requirements.
5 . Added a bonus step.

2016-12-16 04:42 UTC, TheWhiteOx commented
Updated Readme:
Descoped some data display requirements.  Got rid of displaying extra fields that required nested API calls.  It was found that the complexity would take too long for students.

2016-12-17 02:56 UTC, merged